### PR TITLE
Create data_notes_for_recreation.md

### LINKED ISSUE #5: Itemize data to be collected from the reference paper
Check the reference paper in `Papers/Climate-Change-and_Naturaldisasters.pdf` and figure out what data the author used. Make a list of what data we need and where we can get it (FRED or whatever)

### PR DESCRIPTION
**Pull request by andrewpwalters**
Adding markdown file of my notes, closes #5

### CODE REVIEW

**Comment by jessegrabowski** [comment]
This file isn't markdown?

**Comment by andrewpwalters** [comment]
Ah you're right! I'm not sure what happened. Just fixed and re-pushed @jessegrabowski

**Comment by andrewpwalters** [comment]
Done. I think the issue was my text editor is used to me editing LaTeX

**Review by jessegrabowski — APPROVED** [review]
LGTM

**Comment by jessegrabowski** [comment]
The pre-commit hook is failing on remote. You need to make sure you're running it on your end before every commit.

**Pull request merged**
