### PR TITLE
Gpcc loader

### LINKED ISSUE #20: Download script for GPCC data
#5  identified the following dataset for measuring precipitation:

(GPCC) Full Data Reanalysis (Version 7.0)

Create a script that checks if this file is in `data/gpcc_precipitation.csv`, and if not downloads and preprocesses it. Preprocessing should render it a panel-style dataframe with (date, ISO3) index and a single column.

### PR DESCRIPTION
**Pull request by CamSalda**
The script downloads and processes the GPCC data. 

I am having a problem: the original file only has long and lat, and I failed miserably trying to convert that into countries. Does anyone know how to do that? I have spent several hours experimenting and searching on Google, but everything fails. 

Closes #20

### CODE REVIEW

**Comment by jessegrabowski** [comment]
You can convert lat/long into countries by using a shapefile and a "spatial join", see the geopandas docs [here](https://geopandas.org/en/stable/docs/user_guide/mergingdata.html#spatial-joins) for an example

**Comment by jessegrabowski** [comment]
This PR also has the world bank work, please merge them or try to keep your work separate. Remember you have to `git branch` from inside main when you start work on a new feature.

**Comment by CamSalda** [comment]
> This PR also has the world bank work, please merge them or try to keep your work separate. Remember you have to `git branch` from inside main when you start work on a new feature.

Yes sorry! I was not doing that.

**Comment by CamSalda** [comment]
> Closes #20

I activated Pycharm to fix it, however I was having a set of conflict problems. Since I already had spent way tooooo muuuuch time fighting with the giant GPCC file. I preferred to close this one and just create a new branch and PR.

**Pull request closed without merging**
