### PR TITLE
adding time series analysis notebook

### LINKED ISSUE #32: Time series statistics
Look at time trends in all of the data (jointly? individually?)

### PR DESCRIPTION
**Pull request by CamSalda**
Adds notebook with the time series analysis.

Closes #32

### CODE REVIEW

**Review by jessegrabowski — CHANGES_REQUESTED** [review]
This is a great start, hits all the "normal" time series things.

I think just from looking at the raw data plots we can see it's all non-stationary. I don't think you need to run any analysis on the raw data. I suggest you:

1. Remove trend somehow (STL is fine, but then create a detrended series by subtracting only the trend component, leave "seasonality" in)
2. Do some tests for seasonality (I suggest you look at the periodigram and make some [seasonal subseries plots](https://otexts.com/fpp3/subseries.html). Periodigram code will look like this:

```
f, Pxx = periodogram(time_series)
max_power_index = np.argmax(Pxx)
dominant_frequency = f[max_power_index]
period_length = int(1 / dominant_frequency)

fig, ax = plt.subplots(figsize=(14, 4))
ax.plot(f, Pxx, label='Periodogram')
ax.scatter(f[max_power_index], Pxx[max_power_index], color='red', label=f'Dominant Frequency: {dominant_frequency:.2f} Hz')
```

It's only valid on detrended data.

3. Re-run ADF/make the acf/pacf plots against the de-trended series.

I would also prefer you make the presentation a bit more compact. For example, plot_acf/pacf takes an axis argument, so you can do `fig, ax= plt.subplots(1, 2)` and plot the two side-by-side.

After that, it would be good to look at co-integration. @andrewpwalters did some work on that, so you can check with him to avoid duplicating work.

**Comment by CamSalda** [comment]
> This is a great start, hits all the "normal" time series things.
> 
> I think just from looking at the raw data plots we can see it's all non-stationary. I don't think you need to run any analysis on the raw data. I suggest you:
> 
> 1. Remove trend somehow (STL is fine, but then create a detrended series by subtracting only the trend component, leave "seasonality" in)
> 2. Do some tests for seasonality (I suggest you look at the periodigram and make some [seasonal subseries plots](https://otexts.com/fpp3/subseries.html). Periodigram code will look like this:
> 
> ```
> f, Pxx = periodogram(time_series)
> max_power_index = np.argmax(Pxx)
> dominant_frequency = f[max_power_index]
> period_length = int(1 / dominant_frequency)
> 
> fig, ax = plt.subplots(figsize=(14, 4))
> ax.plot(f, Pxx, label='Periodogram')
> ax.scatter(f[max_power_index], Pxx[max_power_index], color='red', label=f'Dominant Frequency: {dominant_frequency:.2f} Hz')
> ```
> 
> It's only valid on detrended data.
> 
> 3. Re-run ADF/make the acf/pacf plots against the de-trended series.
> 
> I would also prefer you make the presentation a bit more compact. For example, plot_acf/pacf takes an axis argument, so you can do `fig, ax= plt.subplots(1, 2)` and plot the two side-by-side.
> 
> After that, it would be good to look at co-integration. @andrewpwalters did some work on that, so you can check with him to avoid duplicating work.

I added the seasonal analysis for the time series in the last push. In the case of events and damages data, the data is annual, so the periodogram did not work. Do you have in mind anything specific for yearly data?

Tomorrow I will do the co-integration analysis.

@jessegrabowski

**Comment by jessegrabowski** [comment]
Periodigram doesn't care about the frequency; what you do mean by didn't work?

**Comment by CamSalda** [comment]
> Periodigram doesn't care about the frequency; what you do mean by didn't work?

Yes, you are right. It was just an NaN problem.

I just added the Periodigrams for all the variables.

**Comment by CamSalda** [comment]
Changes made and pending review @jessegrabowski

**Comment by jessegrabowski** [comment]
General comment: There's not much commentary here -- what can we conclude? Should we be worried about modeling these variables as time series, or does just modeling a trend (or removing it via differencing) suffice?

**Comment by CamSalda** [comment]
<p>Sure. Done.</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/64/discussion/#comment-2222427034'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Yes, it does. I included the test. I found cointegration for the level variables, but not for the first difference versions.</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/64/discussion/#comment-2222427057'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
Changes required done @jessegrabowski

**Review by jessegrabowski — APPROVED** [review]

**Pull request merged**
