### PR TITLE
Adding eda_EM-DAT closes #23

### LINKED ISSUE #23: Basic EDA for the EM-DAT database
Start a notebook to do EDA (exploratory data analysis) on the EM-DAT dataset. EM-DAT is processed into two different datasets, so this issue relates to both. For every type of event we're interested in, we should look at basic descriptive stats. This will get complex because we can slice the dataset in a number of different ways. I propose:

1. Look at global statistics (i.e. "fully pooled")
2. Slice across time. Here we're looking for evidence of distribution shift.
3. Group into regions (continents? finer?)
4. Look at Laos specifically.

When #19 gets merged, it will be good to look at trends between countries similar to Lao; we could use the dataset from #19 to find the k-nearest neighbors to Laos in the feature space and see 1) who they are, and 2) what their disaster trends look like.

We also need to check the effects of the filters used in the replication paper specifically, so make some stats before and after applying those filters. Check #5 for details.

*IMPORTANT* -- time series and geospatial analysis (ACF/PACF/correlation, etc) are **NOT** in the scope of this issue. Keep this one super basic, but extremely through.

### PR DESCRIPTION
**Pull request by CamSalda**
First draft. It is incomplete closes #23

### CODE REVIEW

**Comment by jessegrabowski** [comment]
This is a great first pass, but it's a bit like drinking from a firehose! 

Can you combine some plots so we can get some high-level comparison? For example, the line plots could be combined so that each line is a continent on one plot. 

Also, use the fancy data loading functions that you wrote, rather than directly using `pd.read_data`. You did all that work, need to use it :)

**Comment by CamSalda** [comment]
> drinking from a firehose!

I just pushed a new version using the function instead of importing the file.

I also plotted all the regions together and normalized them.

The only things pending are the histograms and K density plots.

**Comment by CamSalda** [comment]
According to our discussions, I added some changes. I feel that there is still no storytelling in the stats.

However, I am starting to think that that is precisely the point: there is no clear pattern or element to highlight with the disaster data. Contrary to what one could think, the number of climate disasters and their damages has not increased.

The only clear element is that with the filters we loose a lot of events, and almost all the events there are for Laos.

**Comment by CamSalda** [comment]
<p>Ok. I will add the log version so we can have both</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2162278513'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Agree!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2162278528'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>My mistake. This actually not the probability, is the mean number of events. I used "Probability" as a title because it was the probability DF.  I just fixed it.</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2162278547'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>As mentioned, this is actually the mean number of events. But even in that case, I think we don't need to normalize.</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2162278567'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
I just pushed a new version addressing all the last comments @jessegrabowski

**Comment by jessegrabowski** [comment]
You need to rebase this branch from main to address the merge conflicts github is complaining about. You can click that "resolve conflicts" button and see where your current branch disagrees with the current main.

**Comment by CamSalda** [comment]
Conflicts solved and pre-commits ran. @jessegrabowski

**Comment by jessegrabowski** [comment]
Great! Can you just delete the 2nd notebook that's in the git history? I think it would also be good to split out the Laos part into a separate notebook and clean it up a bit. Right now the graphs are blank -- I that's a consequence of the filter, but since laos is our main point, we should explore what little data there is...

**Comment by CamSalda** [comment]
<p>Understood and done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843579'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Understood and done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843607'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843555'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>That is very cool! Done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843412'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843441'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843468'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by CamSalda** [comment]
<p>Solvingthis was wayyyyyyyy more complex than what I expected. But I think it is finally done.</p>

---

 <a href='https://app.reviewnb.com/jessegrabowski/laos-climate-change/pull/36/discussion/#comment-2178843497'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jessegrabowski — APPROVED** [review]
Looks great. This ended up being quite an exhaustive analysis. Great work!

**Pull request merged**
