### PR TITLE
Adding the initial spatial model for EM-DAT #45

### LINKED ISSUE #45: Get familiar with geospatial modeling in PyMC
For geospatial modeling, we have two choices:

1. Continuous features, using a Gaussian Process
2. Point-patterns, using ICAR.

For me, (2) is more credible, because we don't have precise location data. Instead, we just know the country.

To close this issue, use the  [BYM example notebook](https://www.pymc.io/projects/examples/en/latest/spatial/nyc_bym.html) to model the number of disasters in a given year (as encoded by our `df_prob`) as a function of the number of events in neighboring locations. 

Ultimately, we want to know if this correlation is changing over time, so you will need to fit one BYM model for each year in a loop. Use a GaussianRandomWalk prior for the spatial correlation variable, to encode the fact that our prior belief is that the correlation should be stable over time. [This notebook](https://gist.github.com/jessegrabowski/7c023c56076abe6720a1dec7d88c55bd) does something similar and should be helpful, but be aware that this case is much simpler.

### PR DESCRIPTION
**Pull request by CamSalda**
This PR adds the first spatial model for EM-DAT. Closes #45.

This is a first draft. Still not ready.

### CODE REVIEW

**Comment by CamSalda** [comment]
I just pushed a final version for review. @jessegrabowski 

Please pay special attention to the the network plotting for the spatial model with regions and subregions.

I am plotting the networks for each disaster. In the case of beta0 it has shape (3,) with one value for each one of the disasters. So I am indexing beta0 for each disaster.

Similar with beta1_pred_region_d[region_idx] and beta2_pred_region_d[subregion_idx].

I think it is correct. But a check is needed.

**Comment by jessegrabowski** [comment]
Can you split the stuff from my notebook out and make this its own thing?

**Comment by CamSalda** [comment]
> Can you split the stuff from my notebook out and make this its own thing?
> 
> If you need to re-use the logic that aligns the ISO codes, it should be moved into a utility function

Sure! done! @jessegrabowski

**Review by jessegrabowski — APPROVED** [review]
Look great. I'd prefer if the ISO stuff was in a utility function, but I'm not going to block you on it.

In the end there actually was some nice spatial effect on flood and storm, which is great. For us, I mean. Not for the people on those sections of the network.

**Pull request merged**
